### ISSUE TITLE
Two instances of the live wallpaper 

### ISSUE THREAD

**Issue by p-7** [TheOathMan/Godot-Android-Live-Wallpaper#1]
Thank you for your work, it's great that you managed to get it working @TheOathMan .

I remember using LIBGDX a long time ago for live wallpapers.
I'm not sure if this interests you, but I believe the issue was resolved there. 

Please check these methods; they might solve part of the problem.
Perhaps it could help.

---
Please see  onSurfaceCreated , onCreate  function in Engine is little diffirent, maybe this help... 

https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidLiveWallpaperService.java#L226

---

Thanks! 
Best regards.

**Comment by TheOathMan** [comment]
Thank you.
I will take a look at their implementation. 
Good luck.

**Comment by TheOathMan** [comment]
I was able to solve the Multiple instances issue. Test the plugin in your device please and let me know if everything is working as intended.
Your reference helped me refine the implementation. Thank you :)

**Comment by p-7** [comment]
Sorry about that, I had to take off... 

I gave it a test run and it seems to be working okay, thanks! :)

**Comment by TheOathMan** [comment]
Thanks, good luck.
